# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FortnoxEx.Model.Customer do
  @moduledoc """
  A complete customer object
  """

  @derive [Poison.Encoder]
  defstruct [
    :"@url",
    :"Name",
    :"Address"
  ]

  @type t :: %__MODULE__{
    :"@url" => String.t | nil,
    :"Name" => String.t | nil,
    :"Address" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.Customer do
  def decode(value, _options) do
    value
  end
end

