# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FortnoxEx.Model.CustomerPartial do
  @moduledoc """
  A partial customer object (from customer list)
  """

  @derive [Poison.Encoder]
  defstruct [
    :"@url",
    :"Address1",
    :"Address2",
    :"City",
    :"CustomerNumber",
    :"Email",
    :"Name",
    :"OrganisationNumber",
    :"Phone",
    :"ZipCode"
  ]

  @type t :: %__MODULE__{
    :"@url" => String.t | nil,
    :"Address1" => String.t | nil,
    :"Address2" => String.t | nil,
    :"City" => String.t | nil,
    :"CustomerNumber" => String.t | nil,
    :"Email" => String.t | nil,
    :"Name" => String.t | nil,
    :"OrganisationNumber" => String.t | nil,
    :"Phone" => String.t | nil,
    :"ZipCode" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.CustomerPartial do
  def decode(value, _options) do
    value
  end
end

