# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FortnoxEx.Model.MetaInformation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"@CurrentPage",
    :"@TotalResources",
    :"@TotalPages"
  ]

  @type t :: %__MODULE__{
    :"@CurrentPage" => integer() | nil,
    :"@TotalResources" => integer() | nil,
    :"@TotalPages" => integer() | nil
  }
end

defimpl Poison.Decoder, for: FortnoxEx.Model.MetaInformation do
  def decode(value, _options) do
    value
  end
end

